# Site title
title: "Ben Souchet"

baseURL: "https://bensouchet.dev/"

# Set the main language you will use
# Before changing value ensure it"s valid with:
# https://schneegans.de/lv/
languageCode: "en-us"
defaultContentLanguage: "en"

# This is highly important to ensure all elements will works as expected
# It's TZ format, the list of all available values can be found at:
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timeZone: "Europe/Paris"

author:
  name: "Ben Souchet"
  email: "contact@bensouchet.dev"
  url: https://bensouchet.dev

copyright: "© Ben Souchet. All Rights Reserved."

params:
  pathImageProfile: "assets/images/profile-picture.png"
  description: "Ben souchet, Software Engineer, formerly at Ubisoft (working among other things on Riders Republic & Trackmania)."
  dateFormat: "DD-MM-YYYY"
  themeStyle:
    primaryColorName: "greece_blue"
    useFontAwesome: true
  siteVerification:
    google: "bSXPVzWB-6vwyd_Bk0mOEbOHhcTngJckdrdQUIC3hqw"
    pinterest: "b8753060db20d1bf70dc95474a88120e"

menu:
  socialLinks:
  - name: LinkedIn
    pre: <i class="fab fa-linkedin fa-fw"></i>
    url: https://www.linkedin.com/in/BenSouchet/
    weight: 1
  - name: Github
    pre: <i class="fab fa-github fa-fw"></i>
    url: https://github.com/BenSouchet
    weight: 2
  - name: Stack Overflow
    pre: <i class="fab fa-stack-overflow fa-fw"></i>
    url: https://stackoverflow.com/users/10797718/ben-souchet
    weight: 3
  - name: E-mail
    pre: <i class="fas fa-at fa-fw"></i>
    url: mailto:contact@bensouchet.dev?body=Hi%20Ben,%0D%0A%0D%0A
    weight: 4

theme: "cyathea"

# --------------------------- #
# ----- AVANCED CONFIG ------ #

timeout: 60000

enableEmoji: true

#enableGitInfo: true

removePathAccents: true

enableRobotsTXT: true

taxonomies:
  _merge: deep
permalinks:
  _merge: deep
markup:
  _merge: deep
frontmatter:
  _merge: deep